### ISSUE TITLE
configure network environment falken service

### ISSUE THREAD

**Issue by MoSyazwan** [google-research/falken#30]
Hi,

I would like to configure Falken Service on an independent server with it own ip instead of localhost. Do I just change the IP address in the service json file only? how bout the environment key in the json that currently only show "local" is there any other value that i can use?. tried looking into the generate sdk config file, but there is only local config (_LOCAL_CONNECTION_CONFIG)

**Comment by hinasakazaki** [comment]
I believe for the SDK side the json should be sufficient. Since doing our open source migration, we haven't tested running the service non-locally, so we'll see.

For launching the service, make sure to update the [launcher](https://github.com/google-research/falken/blob/main/service/launcher.py#L39) -- probably obvious, but making sure that's what you mean.

**Comment by MoSyazwan** [comment]
> I believe for the SDK side the json should be sufficient. Since doing our open source migration, we haven't tested running the service non-locally, so we'll see.
> 
> For launching the service, make sure to update the [launcher](https://github.com/google-research/falken/blob/main/service/launcher.py#L39) -- probably obvious, but making sure that's what you mean.

awesome,thank you.
